StanfordBDHG/.github

- .github/workflows/build-and-test-xcodebuild.yml
- The current code coverage collection is sometimes not generating coverage for mixed SPM and Xcode projects. This PR removes the flag to rely on Xcode projects to enable the collection of code coverage in the Xcode project scheme editor.
> Remove Automatic Code Coverage Generation

- .github/workflows/build-and-test-xcodebuild-spm.yml
The current xcodebuild SPM workflow fails when we add dependencies to the CardinalKit Swift Package.
We address this by adding a explicit flag to resolve dependencies beforehand.
> Resolve Dependencies Before Building Project for SPM Xcodebuild

- .github/workflows/build-and-test-xcodebuild-spm.yml
- .github/workflows/build-and-test-xcodebuild.yml
The xcodebuild command outputs are currently hard to read and understand if a build error occurs.
Using xcpretty provides a better output for the GitHub Action runs.
> Use xcpretty

- .github/workflows/xcodebuild-or-fastlane.yml
- Adds a `cacheDerivedData` flag.
- Detect self-hosted GitHub runners using the `selfhosted` environment value.
> Self-Hosted Github Action Runner Detection & Make Caching Configurable 

- .github/workflows/xcodebuild-or-fastlane.yml
- The Resolve Package Dependencies Step might sometimes fail as xcodebuild has a problem of parsing swift packages on a first try.
This PR addresses this issue by ignoring the outcome of the package revolve step.
> Ignore Outcome of the Resolve Package Dependencies Step

- .github/workflows/xcodebuild-or-fastlane.yml
- Uses the path for the artifact upload.
> Use Path for the Artifact Upload

- .github/workflows/xcodebuild-or-fastlane.yml
- Enables the selection of an Xcode release on self-hosted runners based on the new setup in https://github.com/StanfordBDHG/VirtualMachine
> Enable Xcode Select on Self-Hosted Runners

- .github/workflows/create-and-upload-coverage-report.yml
- The current setup uses an old version of Xcode and macOS to upload coverage reports.
- Switches the new version to macOS 13
> Use macOS 13 for the Upload of Coverage Reports

- .github/workflows/xcodebuild-or-fastlane.yml
- Uses macOS 13 as the default OS
> Use macOS 13 as the Default Runner on GitHub Hosted Action Runners

- .github/workflows/xcodebuild-or-fastlane.yml
- Code QL currently does not work on self-hosted runners.
- We enforce this rule by checking if the Action is running on a self-hosted runner.
> Update Action Setup & Exclude Executing CodeQL on Self-Hosted Runners

- .github/workflows/xcodebuild-or-fastlane.yml
Currently, it is not possible to modify the behavior of the `actions/checkout` step of the `xcodebuild-or-fastlane` workflow. This might be desired for more custom project setup where, e.g., submodules should be checked out.
This PR adds two new inputs to the `xcodebuild-or-fastlane` workflow to allow specifying the `token` and `submodules` option of the checkout actions to allow (1) automatic checkout of submodules and (2) allow checkout of private submodules.
* Added `checkout_token` and `checkout_submodules` inputs for the `xcodebuild-or-fastlane` workflow.
- This is used within https://github.com/StanfordBDHG/NAMS/pull/19
This [action run](https://github.com/StanfordBDHG/NAMS/actions/runs/6235410706/job/16924569696) verifies functionality of the updated action. The `codeql` job still …
> Add ability to specify PAT and submodule inputs for checkout action

- .github/workflows/xcodebuild-or-fastlane.yml
Recent PR #29 added the functionality to supply a PAT for checkout. This functionality was tested wrongfully (oversight where one confused the successful xcodebuild-or-fastlane of `StanfordSpezi/.github` with this repo).
This PR addresses the issue when not supplying a `checkout_token` by specifying the default `gitHub.token`. The checkout action failed to do so when supplying an empty token.
* Fixed an issue with executing the `xcodebuild-or-fastlane` action when not supplying a `checkout_token`.
Originally implemented in #29.
Functionality was verified by [this CI run](https://github.com/StanfordBDHG/NAMS/actions/runs/6303304333/job/17112269072). The CodeQL step runs the action without supplying a `checkout_token`.
This time it was taken care of the CodeQL action runs the same …
> Fix xcodebuild-or-fastlane when not supplying checkout_token

- .github/workflows/xcodebuild-or-fastlane.yml
- Some deployments, such as watchOS apps might require a secondary provisioning profile.
- Adds configurations to enable the configuration of a secondary provisioning profile.
> Allow Secondary Provisioning Profiles

- .github/workflows/docker-build-and-push.yml
- .github/workflows/docker-compose-test.yml
- .github/workflows/eslint.yml
- .github/workflows/nextjs-github-pages.yml
- .github/workflows/npm-test-and-coverage.yml
- Adds reusable workflows for Node.JS builds and related functionality
> Add Node JS Workflows

- .github/workflows/firebase-deploy.yml
- .github/workflows/xcodebuild-or-fastlane.yml
- Adds mechanism to provide a Google services info plist using GitHub secrets
- Add mechanism to deploy a firebase project using a reusable function
> Add Firebase Deployment GitHub Actions and Capabilities

- .github/workflows/archive.yml
- .github/workflows/xcframework.yml
- CONTRIBUTORS.md
At the moment, the StanfordBDHG fork of [llama.cpp](https://github.com/StanfordBDHG/llama.cpp) as well as the fork of [ResearchKit](https://github.com/StanfordBDHG/ResearchKit) require a GitHub Actions workflow that archives a scheme and creates an XCFramework that is then published in a tagged release. 
As both of these repositories need these functionalities, there is substantial code duplication.
- Add reusable GitHub Action workflows that archive a scheme and create an XCFramework.
Provided within the GitHub Action workflow files.
Workflows have been tested manually.
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing …
> Archive Scheme and Create XCFramework workflows

- .github/workflows/xcframework.yml
- CONTRIBUTORS.md
- README.md
At the moment, the `xcframework.yml` reusable GitHub Action commits the created XCFramework file to a respective branch with the regular GitHub Access Token that is passed to every action. However, if the respective branch has some branch protections (e.g. on the `main` branch), the default access rights of the token won't be sufficient. 
- XCFramework action now takes a [PAT](https://docs.github.com/en/enterprise-server@3.6/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) and an author name/email that are used to commit the created XCFramework file to the respective branch. 
Included in the workflow files
Manually tested
By submitting creating this pull request, you agree to follow our [Code of …
> Commit XCFramework via PAT

- .github/workflows/docker-compose-test.yml
We may need to pass secrets as environment variables when testing with docker, but there is currently no method to do this.
Allows setting an `ENV_FILE` secret which will be written into a `.env` file before running the `docker-compose` command.
> Allows for passing secrets to the docker-compose-test workflow via a `.env` file

- .github/workflows/xcodebuild-or-fastlane.yml
As of now, there is no option to adjust the build configuration of the `xcodebuild-or-fastlane.yml` GitHub Action.
This functionality would be very useful, especially for important production builds or repos that rely on low-layer Swift functionality. 
- Add build configuration parameter to `xcodebuild-or-fastlane.yml` to enable `Debug` or `Release` builds
Proper documentation of parameter
Tested in the https://github.com/StanfordSpezi/.github repo which contains a very similar GitHub action.
> Add build configuration parameter to enable `Debug` or `Release` builds

- .github/workflows/action-release-tag.yml
- .github/workflows/create-and-upload-coverage-report.yml
- .github/workflows/reuse.yml
- .github/workflows/swiftlint.yml
- .github/workflows/xcodebuild-or-fastlane.yml
This PR upgrades the actions to the new v4 version of the upload- and download-artifact actions. This results in a dramatic speed increase when uploading and download artifacts.
The workflow files from this PR were tested within this [action run](https://github.com/StanfordBDHG/XCTestExtensions/actions/runs/7934290919). You can compare timings to the [previous run](https://github.com/StanfordBDHG/XCTestExtensions/actions/runs/7927029084). Comparing these two examples, the coverage download takes 1s instead of 24s. Uploading takes 1s instead of 8s (for a successful run with this example project). 
* Speed increase uploading and downloading code coverage artifacts.
--
These changes were tested in the above linked action runs.
By submitting creating this pull request, you agree to follow our …
> Upgrade to new efficient artifact actions + mac code sign identity

- .github/workflows/archive.yml
- .github/workflows/docker-build-and-push.yml
- .github/workflows/eslint.yml
- .github/workflows/xcframework.yml
We upgraded our code-coverage artifact upload and download actions to use the new `v4` version (see #52). Our xcframework creation process and docker container actions still use the old, slow v3 actions. This PR upgrades them as well.
* Increased performance for file uploads in xcframework creation
> Upgrade artifact actions for archive and docker actions

- .github/workflows/archive.yml
- .github/workflows/xcframework.yml
Currently, the XCArchives and XCFramework actions don't preserve symlinks, resulting in build failures for using XCFrameworks on the macOS platform.
- Preserve symlinks in XCArchives and XCFramework
-
Tested with llama.cpp XCFramework building
> Preserve symlinks in XCArchives and XCFramework

- .github/workflows/xcodebuild-or-fastlane.yml
Xcode projects relying on package plugins do not run successfully with our Xcode build workflow.
To resolve this issue an additional build argument should be added to skip the plugin validation.
- add build argument skipPackagePluginValidation to Xcode build command in the Xcode build workflow
> add flag to xcodebuild to skip package plugin validation

- .github/workflows/create-and-upload-coverage-report.yml
- .github/workflows/npm-test-and-coverage.yml
This PR migrates to the latest CodeCov action.
Note that v4 includes breaking changes. Every upload requires a token now. However, current upload is broken anyways.
* Upgrade codecov action.
> Migrate to CodeCov v4

- .github/workflows/xcodebuild-or-fastlane.yml
- Improve Automated Firebase Emulator Selection for Fastlane Builds
- Fixes an issue where cloud functions were not properly executed as they required a fully configured Admin SDK including permissions of a service account (https://github.com/StanfordBDHG/PediatricAppleWatchStudy/pull/55)
> Improve Automated Firebase Emulator Selection for Fastlane Builds

- .github/workflows/docc-github-pages.yml
- .github/workflows/xcodebuild-or-fastlane.yml
- Installed xcbeautify
- Reusable DocC Documentation Deployment
> xcbeautify & Reusable DocC Documentation Deployment

- .github/workflows/archive.yml
- .github/workflows/xcframework.yml
- Improve XCFramework Building
> Improve XCFramework Building

- .github/workflows/archive.yml
- .github/workflows/xcframework-commit-and-release.yml
- .github/workflows/xcframework.yml
- Improve XCFramework Creation
> Improve XCFramework Creation

- .github/workflows/eslint.yml
- Addresses a permissions errors that `GITHUB_TOKEN` doesn't have permissions to write checks form a public fork. CC: @arkadiuszbachorski
> Fix ESLint Fork Setup

- .github/workflows/npm-test-and-coverage.yml
- There is currently no way to use a different working directory for the GitHub action.
- Add Working Directory Option to the Test and Coverage NPM Workflow
> Add Working Directory Option to the Test and Coverage NPM Workflow

- .github/workflows/firebase-deploy.yml
- There is no way to configure the node version for the firebase deployment
- Update Firebase Deployment to Allow Specifying a Node Version
> Update Firebase Deployment to Allow Specifying a Node Version

- .github/workflows/xcodebuild-or-fastlane.yml
- Update GitHub Action from Spezi Org
> Update GitHub Action from Spezi Org

- .github/workflows/firebase-deploy.yml
https://github.com/StanfordBDHG/.github/pull/82 aims to achieve the same effect. We need to do it through `.env` file creation, because otherwise values aren't properly propagated to build process.
* Add the ability to inject env variables through .env file creation
I updated created test deployment of Web-Frontend successfully with this branch. 
> Add the ability to inject env variables through .env file creation

- .github/workflows/xcodebuild-or-fastlane.yml
In the ENGAGE-HF project, when we seed the emulator using the `npm run serve:seeded` command, the following command executes under the hood: `firebase emulators:exec --only auth,firestore,functions,storage --ui "npm run serve:seed && read -rd \"\""`. This spins up an emulator instance for the duration of the execution of the `"npm run serve:seed && read -rd \"\""` calls. `npm run serve:seed` executes the required functions to seed the emulator, and the `read -rd \"\"` then causes the emulator to continue running until the user cancels the operation.
However, when integrating the seeding functionality into the CI for ENGAGE, we need to be able to have a seeded instance of the emulator for the duration of the fastlane testing call. The `read -rd \"\"` won't work for the self-hosted runner, …
> Add input for custom command in firebase emulators:exec

- .github/workflows/docc-github-pages.yml
- Old iOS simulators are removed from newer runner images.
- Update the action to use an iPhone 16 Simulator
> Update the Simulator for the Xcode Documentation Building

- .github/workflows/archive.yml
- .github/workflows/create-and-upload-coverage-report.yml
- .github/workflows/docc-github-pages.yml
- .github/workflows/periphery.yml
- .github/workflows/xcframework.yml
- .github/workflows/xcodebuild-or-fastlane.yml
- Update to macOS 15-based Runners to Sync with Self-Hosted Runners
> Update to macOS 15-based Runners to Sync with Self-Hosted Runners

- .github/workflows/markdown-link-check.yml
- Replace Markdown Link check with Linkspector
> Move to Linkspector

- .github/workflows/npm-publish-package.yml
Closes #86 
* Add reusable action for publishing NPM packages
I tested it within design system - https://github.com/StanfordSpezi/spezi-web-design-system/actions/runs/12872660105
> Add reusable action for publishing NPM packages

- .github/workflows/npm-publish-package.yml
If NPM package is nested deeply into repository, there is a need to specify working directory and `cache-dependency-path`. 
* Add cache dependency path param to "NPM Publish package"
* Improve NPM token description
* Add working directory param
> Support nested directories in "NPM Publish package"

- .github/workflows/markdown-link-check.yml
`localhost` URLs are checked by Linkspector. Example of failing action: https://github.com/StanfordBDHG/ENGAGE-HF-Web-Frontend/pull/116/checks?check_run_id=36385190565
* Add localhost to ignored Linkspector URLs
Tested here:
https://github.com/StanfordBDHG/ENGAGE-HF-Web-Frontend/pull/117/checks?check_run_id=36434336444
> Add localhost to ignored Linkspector URLs

- .github/pull_request_template.md
- .github/workflows/periphery.yml
- SECURITY.md
The periphery action currently always runs in `--strict` mode, which turns all warnings into errors (or, rather, if any warnings are encountered, the command will fail).
This behaviour is desired in the vast majority of cases, but there are exceptions.
(eg, if you're implementing a soon-to-be-used-but-currently-still-unused component, it would be valid to temporarily have technically unused code in the codebase.)
This flag allows for supporting this.
n/a
n/a
n/a
> periphery action: add flag to control `--strict` mode

- .github/workflows/markdown-link-check.yml
- README.md
With a recent update in linkspector, it no longer accepts RegEx for ignore and replacement patterns.
To unblock our PRs, I am hence changing the default configuration.
The issue has been reported [here](https://github.com/UmbrellaDocs/linkspector/issues/109)
* Hardcode the version to the last working on, i.e., 1.2.5
|Before|After|
|--|--|
| After adding "localhost" to the README in https://github.com/StanfordBDHG/.github/pull/106/commits/ec703252e30dd6001df8c6db3cfb923265edb460 <img width="1095" alt="image" src="https://github.com/user-attachments/assets/435a00c2-5c50-4182-864c-14cef8cb1ebd"/> |  <img width="1101" alt="image" src="https://github.com/user-attachments/assets/34e55c30-277b-48cd-85bd-b160aa503ddd" /> |
By creating and submitting this pull request, you agree to follow our …
> Fix Linkspector RegEx Bug

- .github/workflows/markdown-link-check.yml
Stacked PRs:
* __->__#107
--- --- ---
With the recent [fix of Linkspector](https://github.com/UmbrellaDocs/linkspector/commit/73a9a304b5b4ff165b090c69247ef28a892aa1c6), the the changes from #106 are no longer needed.
* Rollback the Linkspector version to V1
See CI
> Rollback to Linkspector Version V1

- .github/workflows/reuse.yml
We're using a very outdated version of the reuse action. This PR updates this workflow step from v1 to v5.
I did some testing with the [StanfordBDHG/xccov2lcov](https://github.com/StanfordBDHG/xccov2lcov) repo, and this should work without requiring any additional changes.
- Upgrade REUSE check action from v1 to v5.
n/a
n/a
> update reuse action from v1 to v5

- .github/workflows/create-and-upload-coverage-report.yml
- .github/workflows/reuse.yml
We're currently using v3 of the codecov action, which is sometimes causing issues, e.g. random timeouts, missing coverage uploads, or problems with new repositories.
Upgrading to v5 will hopefully increase stability here.
Since, somewhere between v3 and v5, codecov seems to have removed native support for xcresult-bundle-based coverage uploads, we need to add an additional step to export the xcresult bundle's coverage data into an `lcov` file.
- upgraded codecov to v5
n/a (if this works as intended, it should not require any changes in other repos that are using the `create-and-upload-coverage-report` workflow.
n/a
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing …
> codecov@v5

- .github/workflows/xcodebuild-or-fastlane.yml
This PR extends the "Check Environment" step to add a `xcrun simctl list` call, and adds a new "Check Available Simulators" step that runs `xcrun xcodebuild -showdestinations`.
The reason why this might be useful is that some (many) of the different repos' build-and-test workflows specify simulators by name, but these simulators aren't necessarily always available (the versions and device names will change with Xcode updates, e.g.) and in some cases are sometimes randomly missing. These changes will hopefully give a little more insight into the actually existing/available simulators.
- added a "check available simulators" step
n/a
n/a (though this will hopefully make testing a little easier)
By creating and submitting this pull request, you agree to follow our [Code of …
> xcodebuild-or-fastlane: add a "check available simulators" step

- .github/workflows/xcodebuild-or-fastlane.yml
Second attempt at #110, which has since been reverted, this time with an extra check to properly handle empty `inputs.scheme` values.
thanks to @jdisho for pointing this out
- added steps to check the simulators available in the environment
n/a
n/a
> bring back the xcodebuild-or-fastlane "check available simulators" step

- .github/workflows/npm-publish-package.yml
`--tag`  parameter allows creating separate release canals for packages. For example, if we want to publish release candidate or experimental release, we cannot omit `--tag` parameter, because this version would become a latest version of the package. If `packageTag` is not provided, it defaults to `"latest"` which is a default for `npm publish`.
* Add packageTag input to npm-publish-package
> Add packageTag input to npm-publish-package

- .github/workflows/xcodebuild-or-fastlane.yml
We currently assume that a repo/project being tested using the `xcodebuild-or-fastlane` action has only a single test plan, and that xcodebuild will correctly identify and auto-select that on its own (which is indeed what's happening).
But there is no support for having multiple test plans, and selecting which of them should be run.
This PR adds just that: we now have a new (optional) `testplan` input, which can be used to instruct xcodebuild to run only that test plan (i.e., only the tests belonging to that test plan).
The immediate use case here is the MyHeartCounts app, which uses separate test plans for its (non-UI) unit tests and its UI tests, and for which we want both sets of tests to run completelt separate from each other.
- added a new optional `testplan` input to the …
> add `testplan` option

- .github/workflows/npm-publish-package.yml
We want to use the release tag version and overwrite the package.json when using the workspaces feature.
N/A
N/A
N/A
> use package tag instead of package.json

- .github/workflows/xcodebuild-or-fastlane.yml
the `RESULTBUNDLE` shell variable's value currently isn't quoted, leading to issues when expanding it in the `xcodebuild` command.
this hasn't been a problem so far since the result bundle names have, until now, never contained spaces.
adding mac catalyst support via the new matrix-based setup, however, will lead to result bundle names containing spaces. this PR fixes this.
- fixed a bug when `inputs.resultBundle` contained spaces
n/a
n/a
> mac catalyst support
