StanfordBDHG/.github

.github/workflows/build-and-test-xcodebuild-spm.yml, .github/workflows/build-and-test-xcodebuild.yml
Add a separate step to resolve the dependencies early.
=> Resolve Dependencies Early

.github/workflows/xcodebuild-or-fastlane.yml
- Improves the cleanup by doing an best-effort approach to remove any created keychain.
=> Improve Cleanup

.github/DISCUSSION_TEMPLATE/cardinalkit.yml, .github/DISCUSSION_TEMPLATE/healthkitonfhir.yml, .github/DISCUSSION_TEMPLATE/ideas.yml, .github/DISCUSSION_TEMPLATE/researchkitonfhir.yml, .github/DISCUSSION_TEMPLATE/show-and-tell.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/internal_change.yml, .github/ISSUE_TEMPLATE/major_feature.yml, .github/ISSUE_TEMPLATE/minor_feature.yml, .github/codecov.yml, .github/pull_request_template.md, .github/release.yml, .github/workflows/create-and-upload-coverage-report.yml, .github/workflows/reuse.yml, .github/workflows/swiftlint.yml, .github/workflows/xcodebuild-or-fastlane.yml, .gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, CONTRIBUTORS.md, FUNDING.yml, README.md, SECURITY.md, SUPPORT.md, assets/biodesign-footer-dark.png.license, assets/biodesign-footer-light.png.license, profile/README.md
- Our Attribution guidelines are currently only provided by examples and not written down in the contributing guidelines.
- This PR updates the contributing guide to define out attribution and licensing documentation in the GitHub organization.
=> Update Contributing Guide

.github/workflows/xcodebuild-or-fastlane.yml
- Empty arguments cause a crash of the build script.
- Also checks agains an empty string
=> Improve the Reliability of the If Statements

.github/workflows/xcodebuild-or-fastlane.yml
- Fix If Statement
- Reverts boolean condition
=> Fix If Statement

.github/workflows/xcodebuild-or-fastlane.yml
- Executing a custom command allows access to the same secrets as fastlane
=> Improve Custom Command Context

.github/DISCUSSION_TEMPLATE/challenges-and-help.yml, .github/DISCUSSION_TEMPLATE/ideas.yml
- The current templates only reflect an old version of the projects we have on GitHub
- Adds new templates and reworks them to be a bit more generic
=> Update GitHub Discussions Templates

.github/pull_request_template.md, .github/pull_request_template.md.license
=> Update PR template

.github/workflows/docker-compose-test.yml
- Fixes the usage of an outdated checkout GitHub Action
=> Update Checkout GitHub Action

.github/workflows/eslint.yml
=> Update ESLint Permissions

.github/workflows/xcframework.yml
- Fixes and issue where the passed in PAT was not used for committing or pushing as it was not used to checkout.
=> Use PAT For Checkout 

.github/workflows/docker-compose-test.yml
Fixes a syntax error in docker-compose-test.yml.
=> Fixes a syntax error in docker-compose-test.yml

.github/workflows/firebase-deploy.yml
- Adds additional documentation about GCP service accounts and Firebase permissions.
=> Documentation Improvements

.github/workflows/archive.yml, .github/workflows/create-and-upload-coverage-report.yml, .github/workflows/xcframework.yml, .github/workflows/xcodebuild-or-fastlane.yml
- Use macOS 14
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
=>  Use macOS 14

.github/workflows/archive.yml, .github/workflows/xcframework.yml
- Adds Ability to Define the SDK in the Archive Action
=> Adds Ability to Define the SDK in the Archive Action

.github/workflows/xcodebuild-or-fastlane.yml
=> Skip Macro Validation

.github/workflows/create-and-upload-coverage-report.yml, .github/workflows/npm-test-and-coverage.yml
- See https://github.com/codecov/codecov-action/issues/1367 for more details. Unfortunately we have not received any response from the codecov team so far; we will investigate other tools and solutions in the meantime or see if we can somehow contribute to codecov to support them.
=> Revert to CodeCov 3 For Now

.github/workflows/firebase-deploy.yml, .github/workflows/xcodebuild-or-fastlane.yml
- Add Option to Configure in Deployment Environments
=> Add Option to Configure in Deployment Environments

.github/workflows/docker-build-and-push.yml, .github/workflows/xcodebuild-or-fastlane.yml
- CodeQL Improvements
- Add Environments
- Improve Multiplatform Builds
=> CodeQL Improvements, Add Environments, And Improve Multiplatform Builds

.github/workflows/periphery.yml
- Adds a Periphery GitHub Action
=> Add Peripery

.github/DISCUSSION_TEMPLATE/challenges-and-help.yml, .github/DISCUSSION_TEMPLATE/ideas.yml, .github/DISCUSSION_TEMPLATE/show-and-tell.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/internal_change.yml, .github/ISSUE_TEMPLATE/major_feature.yml, .github/ISSUE_TEMPLATE/minor_feature.yml, .github/codecov.yml, .github/workflows/action-release-tag.yml, .github/workflows/archive.yml, .github/workflows/create-and-upload-coverage-report.yml, .github/workflows/docc-github-pages.yml, .github/workflows/docker-build-and-push.yml, .github/workflows/eslint.yml, .github/workflows/firebase-deploy.yml, .github/workflows/markdown-link-check.yml, .github/workflows/nextjs-github-pages.yml, .github/workflows/npm-test-and-coverage.yml, .github/workflows/periphery.yml, .github/workflows/reuse.yml, .github/workflows/test.yml, .github/workflows/xcframework-commit-and-release.yml, .github/workflows/xcframework.yml, .github/workflows/xcodebuild-or-fastlane.yml, .yamllint.yml
- There is no uniform setup for the YML files in this repo.
- Uniform setup and add a linter GitHub Action
=> Update GitHub Actions & Lint

.github/workflows/npm-test-and-coverage.yml
=> Update CodeCov Upload

.github/workflows/npm-test-and-coverage.yml
- Update CodeCov to Fail If Upload Fails
=> Update CodeCov to Fail If Upload Fails

.github/workflows/xcodebuild-or-fastlane.yml
- Update to iPhone 16 As Default Device & Sync with Stanford Spezi
=> Update to iPhone 16 As Default Device & Sync with Stanford Spezi

.github/workflows/xcodebuild-or-fastlane.yml
- CodeQL is failing on GitHub hosted runners: https://github.com/github/codeql-action/issues/2506#issuecomment-2594033147
- Fix CodeQL Execution on GitHub Hosted Runners
=> Fix CodeQL Execution on GitHub Hosted Runners

.github/workflows/periphery.yml
=> Cleanup Periphery

.github/workflows/xcodebuild-or-fastlane.yml
Reverts StanfordBDHG/.github#110
=> Revert "xcodebuild-or-fastlane: add a "check available simulators" step"

.github/workflows/eslint.yml, .github/workflows/firebase-deploy.yml, .github/workflows/nextjs-github-pages.yml, .github/workflows/npm-publish-package.yml, .github/workflows/npm-test-and-coverage.yml
Closes #102 
* Update used Node version to LTS v22
* Make sure description of `nodeVersion` argument is consistent
=> Update used Node version

.github/workflows/format-release-notes.yml
- Format Release Notes GitHub Action
=> Format Release Notes GitHub Action

.github/workflows/npm-publish-package.yml
Minor PR changing the parameter name in the npm publish script to workspaces.
N/A
N/A
N/A
=> Rename Workspace -> Workspaces

.github/workflows/breaking-changes.yml
This PR adds @bauer-andreas' API compatibility check action to the BDHG org's .github repo.
- added API compatibilty check workflow
n/a
n/a
=> add api compat action

.github/workflows/archive.yml, .github/workflows/breaking-changes.yml, .github/workflows/create-and-upload-coverage-report.yml, .github/workflows/docc-github-pages.yml, .github/workflows/periphery.yml, .github/workflows/xcframework.yml, .github/workflows/xcodebuild-or-fastlane.yml
=> Update to macOS 26

.github/workflows/swiftlint.yml
- Added input for project path with default value.
=> Enhance swiftlint.yml With Path Input
